### PR TITLE
Need to fix black version

### PR DESCRIPTION
**Pull request by TheFieryLynx**
it fixes broken dependencies from this issue: https://github.com/pulp/pulp_ansible/issues/1366

### CODE REVIEW

**Review by mdellweg — CHANGES_REQUESTED** [review]
Nope, black is just not a requirement of pulp_ansible. We use it for linting, that's it.

**Comment by mdellweg** [comment]
But no one piece of the software should depend on black. It's a dev tool.

**Comment by TheFieryLynx** [comment]
In this issue: https://github.com/pulp/pulp_ansible/issues/1366 I have described in more detail the sequence of steps and configuration

**Comment by mdellweg** [comment]
I have another PR opend against 0.16. Also this issue should not appear on the main branch anyway. Closing this PR.

**Pull request closed without merging**
