### PR TITLE
Make collection namespace max_length consistent in models

### PR DESCRIPTION
**Pull request by awcrosby**
Make CollectionVersion.namespace max_length match Collection.namespace

https://pulp.plan.io/issues/8078
closes #8078

### CODE REVIEW

**Review by fao89 — COMMENTED** [review]
it is missing the migration

**Review by newswangerd — APPROVED** [review]
changing the max length doesn't require migrations, right?

**Comment by bmbouter** [comment]
It does require a migration, e.g. here is what the previous field length change generated: https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/app/migrations/0025_increase_collection_version_version_size.py

**Comment by fao89** [comment]
closing in favor of https://github.com/pulp/pulp_ansible/pull/504

**Pull request closed without merging**
