### PR TITLE
Add collection version signature model resource

### LINKED ISSUE #844: As a user i want to export signatures with collection versions

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #844

### CODE REVIEW

**Comment by bmbouter** [comment]
I'm not very familiar with import/export, but I'm happy to see this. Besides @ggainey who is the other import/export SME to review?

**Comment by fao89** [comment]
> I'm not very familiar with import/export, but I'm happy to see this. Besides @ggainey who is the other import/export SME to review?

@gerrod3

**Review by gerrod3 — COMMENTED** [review]
Looks good. has this been tested?

**Comment by ggainey** [comment]
> Looks good. has this been tested?

If the remote being set up here : https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/tests/functional/api/test_export.py#L43 has signed-collections, then test_export and test_import will test this code.

**Comment by ggainey** [comment]
> > > Looks good. has this been tested?
> > 
> > 
> > If the remote being set up here : https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/tests/functional/api/test_export.py#L43 has signed-collections, then test_export and test_import will test this code.
> 
> I highly doubt that. (The main reason why i hesitate to undraft this PR.)

I wouldn't want to accept this until we've seen it export and import of a signed collection at least once - even if that was a manual one-off test. I'm not conversant enough w/ ansible collections to know what's involved, alas.

**Comment by bmbouter** [comment]
I really think we should look at the CI having a two-container setup and importing from one to the other.

**Comment by mdellweg** [comment]
Now that i finally came around to look into this it triggered this known issue:

https://github.com/django-import-export/django-import-export/issues/740

**Comment by mdellweg** [comment]
Finally i realized, that the ModelResource was alright altogether. The test just had the wrong assertions. XD

**Comment by mdellweg** [comment]
Last thing to check: Does the migration convert the existing bytes records properly into strings.

**Review by gerrod3 — APPROVED** [review]

**Pull request merged**
