### PR TITLE
Removing manifest and files from metadata endpoints.

### PR DESCRIPTION
**Pull request by fao89**
https://pulp.plan.io/issues/8264
closes #8264

### CODE REVIEW

**Comment by fao89** [comment]
`/api/v3/collections/pulp/pulp_installer/versions/`
image


`/api/v3/collections/pulp/pulp_installer/versions/3.10.0/`
image


`/api/v3/collection_versions/all/`
image

**Review by gerrod3 — APPROVED** [review]

**Review by bmbouter — APPROVED** [review]
This looks good to me.

**Comment by rochacbruno** [comment]
I am testing it with AH locally, will give my review ASAP

**Review by rochacbruno — APPROVED** [review]
:shipit:

**Pull request merged**
