### PR TITLE
Create a roles content endpoint in the api

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #3549
https://pulp.plan.io/issues/3549

New endpoints:

```
/api/v3/content/ansible/roles/
/api/v3/content/ansible/roles/<role_pk>/versions/
```

### CODE REVIEW

**Comment by bmbouter** [comment]
I tested this code and it works really nicely. The two endpoints show off sync'd content nicely.

**Comment by bmbouter** [comment]
So is it possible with this PR to upload a AnsibleRoleVersion to an empty Pulp instance?

**Comment by daviddavis** [comment]
@bmbouter you can currently upload a role version artifact. That works. You cannot create a AnsibleRoleVersion though. I added a NotImplementedError to this path:

https://github.com/pulp/pulp_ansible/pull/6/files#diff-bfcb746c009dd53f978b79fa78e902a1R71

And I left this bit of functionality for this ticket:

https://pulp.plan.io/issues/3529

**Comment by daviddavis** [comment]
There is one downside to switching from Model to Content and that is the relationship to Artifact. I don't think it's a big one though as long as we make sure not to expose it in the REST API. I did consider maybe creating a new class in pulpcore (e.g. ArtifactlessContent) that could be extended by Content and AnsibleRole.

The benefit of the change is that Model couldn't be used in the Content viewset—which I think has to do with the master-model stuff. Another benefit is that we get the natural keys methods which don't seem to do much ATM though. And lastly, if we ever add some future functionality to Content, AnsibleRole will automatically have it.

**Pull request merged**
