### PR TITLE
Fix improper query on CollectionVersionViewset

### PR DESCRIPTION
**Pull request by gerrod3**
fixes: #813

### CODE REVIEW

**Comment by rochacbruno** [comment]
@gerrod3 it fixed the filtering problem, however the signatures: [] field is always empty now, I tested with signed and unsigned collection

**Comment by gerrod3** [comment]
> @gerrod3 it fixed the filtering problem, however the signatures: [] field is always empty now, I tested with signed and unsigned collection

Which endpoint are you testing and what is your workflow for testing?

**Comment by rochacbruno** [comment]
@gerrod3 my workflow is, on a galaxy system.

- I uploaded footest/fooh/1.0.0/
- I uploaded bartest/barh/1.0.0/
- Both ends up on `/staging/` repository on galaxy waiting for approval
- I approve only `footest/fooh/1.0.0/` while the other one (prefixed with `bar`) is still on staging, the approved one `(foo` prefix) is signed and then moved to `/published` repo.

GET http://0.0.0.0:5001/api/automation-hub/content/published/v3/collections/?name=fooh
```json
{
  "meta": {
    "count": 1
  },
  "links": {
    "first": "/api/automation-hub/content/published/v3/collections/?limit=10&offset=0",
    "previous": null,
    "next": null,
    "last": "/api/automation-hub/content/published/v3/collections/?limit=10&offset=0"
  },
  "data": [
    {
      "href": "/api/automation-hub/content/published/v3/collections/footest/fooh/",
      "namespace": "footest",
      "name": "fooh",
      "deprecated": false,
      "versions_url": "/api/automation-hub/content/published/v3/collections/footest/fooh/versions/",
      "highest_version": {
        "href": "/api/automation-hub/content/published/v3/collections/footest/fooh/versions/1.0.0/",
        "version": "1.0.0"
      },
      "created_at": "2022-02-01T11:48:34.541288Z",
      "updated_at": "2022-02-01T11:49:40.629345Z"
    }
  ]
}
```
GET http://0.0.0.0:5001/api/automation-hub/content/staging/v3/collections/?name=barh
```json
{
  "meta": {
    "count": 1
  },
  "links": {
    "first": "/api/automation-hub/content/staging/v3/collections/?limit=10&name=barh&offset=0",
    "previous": null,
    "next": null,
    "last": "/api/automation-hub/content/staging/v3/collections/?limit=10&name=barh&offset=0"
  },
  "data": [
    {
      "href": "/api/automation-hub/content/staging/v3/collections/bartest/barh/",
      "namespace": "bartest",
      "name": "barh",
      "deprecated": false,
      "versions_url": "/api/automation-hub/content/staging/v3/collections/bartest/barh/versions/",
      "highest_version": {
        "href": "/api/automation-hub/content/staging/v3/collections/bartest/barh/versions/5.0.0/",
        "version": "5.0.0"
      },
      "created_at": "2022-02-01T11:49:15.574095Z",
      "updated_at": "2022-02-01T11:49:40.673627Z"
    }
  ]
}
```
- Now I go to `/api/automation-hub/content/published/v3/collections/footest/fooh/versions/1.0.0/`
GET http://0.0.0.0:5001/api/automation-hub/content/published/v3/collections/footest/fooh/versions/1.0.0/

```json
{
  "id": "603fa7c9-53b5-4f31-8cc8-086a9feb7e42",
  "version": "1.0.0",
  "href": "/api/automation-hub/content/published/v3/collections/footest/fooh/versions/1.0.0/",
  "created_at": "2022-02-01T11:48:34.541288Z",
  "updated_at": "2022-02-01T11:48:34.541307Z",
  "requires_ansible": ">=2",
  "artifact": {
    "filename": "footest-fooh-1.0.0.tar.gz",
    "sha256": "37dde895285b12da213dd2ad038e2e1350fb9dfe39d9733d69cedbefe3108142",
    "size": 1564
  },
  "collection": {
    "id": "3a2a4ecc-7f45-47cf-89ba-b31966a53547",
    "name": "fooh",
    "href": "/api/automation-hub/content/published/v3/collections/footest/fooh/"
  },
  "download_url": "http://localhost:5001/api/automation-hub/v3/artifacts/collections/published/footest-fooh-1.0.0.tar.gz",
  "name": "fooh",
  "namespace": {
    "name": "footest"
  },
  "signatures": [],
  "metadata": {
    "authors": [
      "Orion User 1"
    ],
    "contents": [],
    "dependencies": {},
    "description": "a collection with some deps on other collections",
    "documentation": "",
    "homepage": "",
    "issues": "",
    "license": [
      "GPL-3.0-or-later"
    ],
    "repository": "http://github.example.com/orionuser1/skeleton",
    "tags": [
      "collectiontest"
    ]
  },
  "git_url": null,
  "git_commit_sha": null,
  "manifest": {},
  "files": {}
}
```
>  The signatures field is empty


- If I go to Django Shell then I have the signature there
```py
In [13]: CollectionVersion.objects.get(
    ...:     name="fooh", namespace="footest", version="1.0.0"
    ...: ).signatures.all()
Out[13]: <BulkTouchQuerySet [<CollectionVersionSignature: pk=35cdd3b9-2fd1-4f1a-a4a2-7de8ad8353e0>]>
```

**Comment by rochacbruno** [comment]
More details

This is the subclass of viewset https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/api/v3/viewsets/collection.py#L172 

It has mixins that extends the serializer context https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/api/v3/viewsets/collection.py#L52-L68

**Comment by rochacbruno** [comment]
@gerrod3 I found that if I sign the collection on the `staging` repo but NOT MOVE then the signatures shows, what happens is that when I move the collection the signature is not moving, so probably the problem is not with signing but with moving logic.

We move content using this

```py
def sign_and_move(signing_service_pk, collection_version_pk, source_repo_pk, dest_repo_pk):
    """Sign collection version and then copy to the destination repo"""
    # Sign while in the source repository
    sign(
        repository_href=source_repo_pk,
        content_hrefs=[collection_version_pk],
        signing_service_href=signing_service_pk
    )
    # Then copy to the destination repo
    source_repo = AnsibleRepository.objects.get(pk=source_repo_pk)
    config = [{
        'source_repo_version': source_repo.latest_version().pk,
        'dest_repo': dest_repo_pk,
        'content': [collection_version_pk],
    }]
    copy_content(config)

    # remove old content from source repo
    _remove_content_from_repository(collection_version_pk, source_repo_pk)
```

I guess it is moving only the collection version while keeping the signature on the source repo.

Should we manually move related signatures?

**Comment by rochacbruno** [comment]
I am not sure if this line 

https://github.com/pulp/pulp_ansible/blob/09a99fa9feff2ea7b89ec26f38cfdb87099c9dc9/pulp_ansible/app/tasks/copy.py#L60

Is handling the copy of signatures or if this must also include the related signatures or if we must do that manually when dispatching.

**Pull request merged**
