### PR TITLE
Port sync to stages

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by mdellweg** [comment]
@pulp/qe it seems like the crud remote tests pass only occasionally.

**Comment by daviddavis** [comment]
@mdellweg this is a community plugin and so the tests aren't maintained by @pulp/qe. I'll try to take a look into the test failure.

By the way, thanks a lot for submitting this PR. It's really appreciated. 👍

**Comment by daviddavis** [comment]
Here's the failure: `{'_content': b'{"policy":["\\"cache_only\\" is not a valid choice."]}'`. Looks like it's being set here in the test randomly. I think maybe we should set DOWNLOAD_POLICIES to only `['immediate']`. AFAIK, this plugin doesn't support lazy syncing (yet).

**Comment by mdellweg** [comment]
Thank you. I think we can try to be bold and just turn it on. I think the stages cover that for us.

**Comment by daviddavis** [comment]
I was thinking we could do that in a follow up PR. Up to you.

**Comment by daviddavis** [comment]
Actually it looks like the policy of 'cache_only' got renamed to 'streamed'. If you could just update [this line in the tests](https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/tests/functional/constants.py#L10), I can merge this PR.

Thanks again @mdellweg.

**Comment by mdellweg** [comment]
@daviddavis Thank you, that worked. :champagne:

**Comment by daviddavis** [comment]
💃🥂🎉🎈

**Pull request merged**
