### PR TITLE
Change Django app label and adjust `endpoint_name`s

### PR DESCRIPTION
**Pull request by goosemania**
re #4279
https://pulp.plan.io/issues/4279

Required PR: https://github.com/pulp/pulp/pull/3836

### CODE REVIEW

**Comment by goosemania** [comment]
FWIW, I didn't change anything [here](https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/app/viewsets.py#L77-L96) since you overwrite `endpoint_pieces` where all the prepending happens.

**Comment by mdellweg** [comment]
@goosemania I'd like to see this being merged. I know, that it might not be all that is needed to get the tests green again, but it certainly does not make matters worse.

**Comment by daviddavis** [comment]
Can you rebase? And then I can merge.

**Comment by goosemania** [comment]
@daviddavis , done.
Tests are failing due to changes in serializer classes.

**Pull request merged**
