### PR TITLE
Sync collection and its dependencies

### PR DESCRIPTION
**Pull request by fao89**
https://pulp.plan.io/issues/7751
closes #7751

### CODE REVIEW

**Comment by fao89** [comment]
Pros:
- fixes the CI
- fixes the dependency issue (with ansible 2.10, more collections will have dependencies)

Cons:
- sync all dependency versions
- one more if on the while loop
- hack the URL, which may cause other issues

Alternative: https://github.com/pulp/pulp_ansible/pull/396

**Comment by daviddavis** [comment]
Does this change properly handle pages?

**Comment by fao89** [comment]
> Does this change properly handle pages?

yes, from the pulp_installer example, it will yield this URL: https://galaxy.ansible.com/api/v2/collections/ansible/posix
which will be appended to the `not_done` and follow the sync workflow.

**Comment by fao89** [comment]
> > Does this change properly handle pages?
> 
> yes, from the pulp_installer example, it will yield this URL: https://galaxy.ansible.com/api/v2/collections/ansible/posix
> which will be appended to the `not_done` and follow the sync workflow.

by our IRC conversation, it does not handle pagination properly

**Comment by fao89** [comment]
> > > Does this change properly handle pages?
> > 
> > 
> > yes, from the pulp_installer example, it will yield this URL: https://galaxy.ansible.com/api/v2/collections/ansible/posix
> > which will be appended to the `not_done` and follow the sync workflow.
> 
> by our IRC conversation, it does not handle pagination properly

this https://github.com/pulp/pulp_ansible/pull/399 should fix the pagination issue

**Pull request closed without merging**
