### PR TITLE
Use Github Issues

### PR DESCRIPTION
**Pull request by fao89**
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Do you think, this should include a preliminary run of towncrier to make sure the merged changelogs point to the right tickets?

**Comment by fao89** [comment]
> Do you think, this should include a preliminary run of towncrier to make sure the merged changelogs point to the right tickets?

I'm not sure, I don't know how towncrier would behave if we run it 2 times for the same version

**Review by gerrod3 — APPROVED** [review]

**Comment by mdellweg** [comment]
> > Do you think, this should include a preliminary run of towncrier to make sure the merged changelogs point to the right tickets?
> 
> I'm not sure, I don't know how towncrier would behave if we run it 2 times for the same version

I would run it for x.y.z-unreleased and adjust the docs by hand in the actual release. The other option is to wait and adjust all the old links at release time. Neither is a nice solution.

**Comment by fao89** [comment]
I think I will manually create these issues on github and change the number of the changelog entries

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
