### PR TITLE
Add Github Actions CI

### PR DESCRIPTION
**Pull request by dralley**
[noissue]

### CODE REVIEW

**Review by daviddavis — APPROVED** [review]
:+1:

**Comment by bmbouter** [comment]
Does this add github actions and things also run on travis?

**Comment by dralley** [comment]
@bmbouter It doesn't disable anything on Travis, yet.

**Review by bmbouter — APPROVED** [review]
Let's do this!

**Comment by dralley** [comment]
@bmbouter https://www.youtube.com/watch?v=mLyOj_QD4a4&t=1m20s

**Comment by dralley** [comment]
I think this is clear to move forwards, the issues in the RPM plugin are specific to the RPM plugin.

**Pull request merged**
