### PR TITLE
Fix bindings issue

### PR DESCRIPTION
**Pull request by fao89**
[noissue]

### CODE REVIEW

**Comment by daviddavis** [comment]
Was this caused by the drf-spectacular upgrade to 0.15?

**Comment by fao89** [comment]
> Was this caused by the drf-spectacular upgrade to 0.15?

yes, it is creating a fake request now

**Review by daviddavis — APPROVED** [review]

**Comment by fao89** [comment]
> Can you add that info to the commit message?

not sure how to communicate that,
make pulp_ansible compatible with drf-spectacular 0.15 ?

**Comment by daviddavis** [comment]
> make pulp_ansible compatible with drf-spectacular 0.15 ?

:+1:

**Pull request merged**
