### PR TITLE
Small changes to match current best practices

### PR DESCRIPTION
**Pull request by dralley**
[noissue]

### CODE REVIEW

**Comment by dralley** [comment]
@fao89  I meant to make this a draft, could you update it?

This won't merge until after 3.11, it's only for testing purposes right now.

**Comment by fao89** [comment]
> @fao89 I meant to make this a draft, could you update it?
> 
> This won't merge until after 3.11, it's only for testing purposes right now.

done!

**Comment by dralley** [comment]
CI failure is unrelated apparently, will rebase after https://github.com/pulp/pulp_ansible/pull/526

**Comment by fao89** [comment]
> CI failure is unrelated apparently, will rebase after #526

CI is fixed now!

**Pull request closed without merging**
