### PR TITLE
remove unnecessary DELETE action for 'set_certified'

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes: https://pulp.plan.io/issues/5711

### CODE REVIEW

**Comment by bmbouter** [comment]
@romanblanco Thanks for this! I apologize our contributing docs are not fully up to date. To accept this can you do a few small things?

1) Can you file a short issue here with the description:  https://pulp.plan.io/projects/ansible_plugin/issues/new
2) Can you include an entry in the CHANGES folder that refers to ^ issue number. See [docs here](https://pulp-ansible.readthedocs.io/en/latest/contributing.html#changelog-update)
3) Can you associate your commit with that issue using [this syntax](https://docs.pulpproject.org/en/3.0/nightly/contributing/git.html#commit-message) in your commit message.

Thanks again, and I'll try to fix these contributing docs for the future.

**Comment by bmbouter** [comment]
^ should get the CI passing for you

**Comment by romanblanco** [comment]
@bmbouter please, restart Travis.

**Comment by bmbouter** [comment]
@romanblanco every time you force push Travis will run. Look at the errors in the job, it's complaining due to black formatting. https://travis-ci.org/pulp/pulp_ansible/jobs/611859747#L440

**Comment by bmbouter** [comment]
Currently CI is failing on 'master' so even if this PR is perfect it will still fail. So this work is effectively blocked. :( We're going to fix that other problem, and then post back here when this is unblocked.

**Comment by daviddavis** [comment]
Thank you @romanblanco!

**Pull request merged**
