### PR TITLE
Disable single commit check.

### PR DESCRIPTION
**Pull request by jctanner**
[noissue]

Signed-off-by: James Tanner <tanner.jc@gmail.com>

### CODE REVIEW

**Comment by awcrosby** [comment]
I believe what works pretty well in galaxy_ng… the PR can have multiple commits that show the history of things being worked, and shows CI passing/failing per commit, and in our repo settings we only have checked the `Allow squash merging` option which ensures a single commit per PR

**Comment by mdellweg** [comment]
The point is, we don't want to enforce a single commit. And yes, i'm sad that this check cannot report as yellow instead of red. It's not marked as "required" though. Anyway, a change like this needs some discussion with the team.
cc @pulp/ansible

**Comment by mdellweg** [comment]
I think you can edit the commit message on squash. So the person pushing the button would be in charge.

**Comment by bmbouter** [comment]
@jctanner why close?

**Comment by bmbouter** [comment]
I made this a formal proposal here: https://discourse.pulpproject.org/t/removing-the-one-commit-check-in-the-ci/639 The idea is to have pulp_ansible try it out and then we can report how we like it.

We need to determine which setting to try first for the allow squash merging config...

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
