### PR TITLE
Repair collection

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Review by jctanner — APPROVED** [review]

**Review by gerrod3 — APPROVED** [review]
Bookkeeping: feature implemented in https://github.com/pulp/pulp_ansible/pull/1174 and https://github.com/pulp/pulp_ansible/pull/1253

**Comment by ipanova** [comment]
I see a backport tag here, please update .feature to .bugfix

**Comment by mdellweg** [comment]
> I see a backport tag here, please update .feature to .bugfix

It's a feature, and technically it's not a backport, because 0.15.0 is not releases yet. I just want to use the patchback machinery to get it in fast.

**Comment by ipanova** [comment]
> > I see a backport tag here, please update .feature to .bugfix
> 
> It's a feature, and technically it's not a backport, because 0.15.0 is not releases yet. I just want to use the patchback machinery to get it in fast.

yes yes, i realized that after i've pressed comment button. you're good to go!

**Pull request merged**
