### PR TITLE
Reduce fetched fields in cv list endpoint to prevent OOMKILL. (#1430)

### PR DESCRIPTION
**Pull request by jctanner**
fixes: #1433

Signed-off-by: James Tanner <tanner.jc@gmail.com>
(cherry picked from commit a52dc98b7056987b127ebdb1331c5bb058d7540b)

### CODE REVIEW

**Comment by mdellweg** [comment]
Looks easy enough. But some how the tests are read. Looks like something is pulling in conflicting yaml library.

**Comment by jctanner** [comment]
Tests are failing due to a missing backport for https://github.com/pulp/pulp_ansible/pull/1417

**Comment by jctanner** [comment]
https://github.com/pulp/pulp_ansible/pull/1436

**Review by mdellweg — APPROVED** [review]

**Comment by jctanner** [comment]
replaced by https://github.com/pulp/pulp_ansible/pull/1438

**Pull request closed without merging**
